name: EssentialsC
version: DEV
main: net.danielonline.Essentials.Essentials
load: STARTUP
author: dandabs
depend: [ProtocolLib, Vault, LiteBans]
api-version: 1.13
authors:
  - pyxxl.
website: https://ccessentials.glitch.me
commands:
  opme:
    description: Get free OP here. Go on, don't you trust me?
    aliases:
      - opget
    permission: cc.player.opme
  info:
    description: Information about Cloudess
    aliases:
      - cloudess
      - cc
      - about
  clear:
    description: Clear your inventory
    aliases:
      - clearinv
      - ci
      - clearinventory
    permission: cc.player.clear
  addspawn:
    description: Add a spawn to the list
    permission: cc.core.addspawn
  ccreload:
    description: Reload the CloudEss configuration
    permission: cc.core.reload
  addpod:
    description: Add a pod to the server core
    permission: cc.core.addpod
  34e61a83-71fb-4374-b6c5-e6a089c504ac:
    description: N-WORDS ARE NOT TOLERATED HERE!!!!!!
  plugins:
    description: See our plugins.
    aliases:
      - pl
      - pluginlist
  rules:
    description: Currently broken
    permission: cc.being.gay.like.dan.which.is.literally.impossible.lol