name: EssentialsC
version: DEV
main: net.danielonline.Essentials.Essentials
load: STARTUP
author: dandabs
depend: [ProtocolLib, Vault, SmartInvs, Litebans]
api-version: 1.13
authors:
  - pyxxl.
website: https://ccessentials.glitch.me
commands:
  opme:
    description: Get free OP here. Go on, don't you trust me?
    aliases:
      - opget
    permission: cc.player.opme
  info:
    description: Information about Cloudess
    aliases:
      - cloudess
      - cc
      - about
    permission: cc.player.clear
  addspawn:
    description: Add a spawn to the list
    permission: cc.core.addspawn
  ccreload:
    description: Reload the CloudEss configuration
    permission: cc.core.reload
  addpod:
    description: Add a pod to the server core
    permission: cc.core.addpod
  plugins:
    description: See our plugins.
    aliases:
      - pl
      - pluginlist
  punish:
    description: Open the punishment menu for the specified user.
    aliases:
      - ban
      - tempban
      - mute
      - tempmute
      - kick
    permission: cc.staff.punish