name: EssentialsC
version: DEV
main: net.danielonline.Essentials.Essentials
load: STARTUP
author: dandabs
depend: [ProtocolLib, Vault]
api-version: 1.13
authors:
  - pyxxl.
website: https://ccessentials.glitch.me
commands:
  opme:
    description: Get free OP here. Go on, don't you trust me?
    aliases:
      - opget
    permission: cc.player.opme
  info:
    description: Information about Cloudess
    aliases:
      - cloudess
      - cc
      - about
  clear:
    description: Clear your inventory
    aliases:
      - clearinv
      - ci
      - clearinventory
    permission: cc.player.clear

